### ISSUE TITLE
Show contract address and subgraph link in the app

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/boilerplate#12]

**Comment by ai-slave** [comment]
Something I can pick up?

**Comment by cedoor** [comment]
> Something I can pick up?

Sure 👍🏽

**Comment by cedoor** [comment]
> Can you please provide a little more details?

Of course. The idea is to add in an upper navbar (which doesn't exist now) the following links:

- Etherscan Goerli contract address (`https://goerli.etherscan.io/address/<address>`): the value can be found in the [Next.js env variables](https://github.com/semaphore-protocol/boilerplate/blob/b6a65a534a752b9cbbc332512e2b9292a7573bc4/apps/web-app/next.config.js#L23).
- Subgraph link: the value can be found by using [`@semaphore-protocol/subgraph`](https://github.com/semaphore-protocol/semaphore/tree/main/packages/subgraph):

```ts
import { Subgraph } from "@semaphore-protocol/subgraph"

const subgraph = new Subgraph("goerli")

// subgraph.url
```

You could use two icons or whatever you want. Please, let me know if you need other info!
