### ISSUE TITLE
Error: could not detect network when tapping join group in frontend

### ISSUE THREAD

**Issue by NOOMA-42** [semaphore-protocol/boilerplate#3]
**Describe the bug**
Error: could not detect network when tapping join group in frontend

**To Reproduce**
following steps in readme

1. 
```bash
yarn start:contracts
```
2. 
```bash
yarn start:web-app
```
3. 
```bash
yarn start:relay
```
4. tap join group in frontend

**Expected behavior**
```
❯ yarn start:relay
Started HTTP relay API at http://localhost:3000/
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.8)
    at Logger.makeError (/Users/paulyu/paul_playground/boilerplate/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/Users/paulyu/paul_playground/boilerplate/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at JsonRpcProvider.<anonymous> (/Users/paulyu/paul_playground/boilerplate/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:444:23)
    at step (/Users/paulyu/paul_playground/boilerplate/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/paulyu/paul_playground/boilerplate/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/paulyu/paul_playground/boilerplate/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```

**Technologies (please complete the following information):**

-   Node.js version: v18.10.0
-   NPM version: 8.19.2
-   Solidity version: 0.8.4

**Additional context**
when I was running the contract, I got following warnging: 
```
You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all.

Please, make sure you are using a supported version of Node.js.

To learn more about which versions of Node.js are supported go to https://hardhat.org/nodejs-versions
```
**My Trial**
https://github.com/ethers-io/ethers.js/issues/1316 here's a similar error message, but it doesn't seems to helps

**Comment by cedoor** [comment]
Hi @NOOMA-42! 

Which version of NodeJS are you using?

Have you created the `.env` file? You can run the following command:

```bash
cp .env.example .env
```

**Comment by NOOMA-42** [comment]
I'm using v18.10.0 for NodeJS. 
I've also created `.env` file as default
```
ETHEREUM_URL=http://localhost:8545
ETHEREUM_CHAIN_ID=1337
ETHEREUM_PRIVATE_KEY=ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
CONTRACT_ADDRESS=0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9
RELAY_URL=http://localhost:3000
REPORT_GAS=false
INFURA_API_KEY=
COINMARKETCAP_API_KEY=
```

> Hi @NOOMA-42!
> 
> Which version of NodeJS are you using?
> 
> Have you created the `.env` file? You can run the following command:
> 
> ```shell
> cp .env.example .env
> ```

**Comment by cedoor** [comment]
Can you check if the Hardhat Ethereum URL is correct when you run `yarn start:contracts`? Is it generating the right contract address (`0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9`)?

**Comment by NOOMA-42** [comment]
Verifier20 contract has been deployed to: 0x5FbDB2315678afecb367f032d93F642f64180aa3
Poseidon library has been deployed to: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
IncrementalBinaryTree library has been deployed to: 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
Semaphore contract has been deployed to: 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9

Greeter contract has been deployed to: 0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9

> Can you check if the Hardhat Ethereum URL is correct when you run `yarn start:contracts`? Is it generating the right contract address (`0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9`)?

**Comment by cedoor** [comment]
I can't reproduce this error :/ The only difference should be the Node.js version, but it looks like it is using the wrong Network URL.

**Comment by NOOMA-42** [comment]
It's the Node.js version causes the error. The hardhat only supports Node.js 16 Gallium LTS release for now and haven't support 18 Hydrogen LTS release. After downgrading Node.js, the error were gone.

**Comment by cedoor** [comment]
> It's the Node.js version causes the error. The hardhat only supports Node.js 16 Gallium LTS release for now and haven't support 18 Hydrogen LTS release. After downgrading Node.js, the error were gone.

Ahn, good to know! Thank you very much!
