### ISSUE TITLE
How to get proofSiblings and proofPathIndices from Identity?

### ISSUE THREAD

**Issue by HiraSiddiqui** [semaphore-protocol/boilerplate#41]
I am trying to find a function in the @semaphore-protocol/group or @semaphore-protocol/identity package that can help me get **proofSiblings** and **proofPathIndices** of a certain identity. 

I want to test out removing a member from a group. I went through the documentation, boilerplate code and the subgraph code but haven't found where to get this information from.

Please guide me to the right direction

**Comment by cedoor** [comment]
Hey @HiraSiddiqui, `proofSiblings` and `proofPathIndices` are part of the `MerkleProof`return value, which you can get by using the `generateMerkleProof` function in the [`@semaphore-protocol/group`](https://github.com/semaphore-protocol/semaphore/tree/main/packages/group#-usage) package.

**Comment by HiraSiddiqui** [comment]
> Hey @HiraSiddiqui, `proofSiblings` and `proofPathIndices` are part of the `MerkleProof`return value, which you can get by using the `generateMerkleProof` function in the [`@semaphore-protocol/group`](https://github.com/semaphore-protocol/semaphore/tree/main/packages/group#-usage) package.

Is there a way to generate this information from smart contract functions?

What if I don't want to keep a local state of the members that are in group, but only want to rely on smart contract state to check which members are part of the group and which are not? 

Is it necessary to maintain an off-chain state of current group members?

**Comment by HiraSiddiqui** [comment]
Alright, this answers my question. Closing the ticket now. Thanks for your help!
