### ISSUE TITLE
Display the group and feedback lists starting with the most recently added info

### ISSUE THREAD

**Issue by vplasencia** [semaphore-protocol/boilerplate#59]
## Description

Right now when you join a group you have to scroll to see you there. The same happens when you send the feedback, you have to scroll to see your feedback. It would be nice to always show the most recently added info.

A quick fix could be to reverse the list before displaying it.

**Comment by vplasencia** [comment]
Hey @varunsh20 ! Yes. Do you want me to assign you this issue?

**Comment by varunsh20** [comment]
Yes sure

**Comment by vplasencia** [comment]
Done! Thank you very much. Let us know if you have questions.

**Comment by varunsh20** [comment]
Please review it and let me know if any changes are required/
