### ISSUE TITLE
Make it easier to go to the first page of the app

### ISSUE THREAD

**Issue by vplasencia** [semaphore-protocol/boilerplate#74]
## Description

The idea is to make it easier to go to the first page of the app. 

To solve this issue, a link could be added to the header, similar to the solution used in the [Semaphore templates](https://github.com/semaphore-protocol/semaphore/blob/main/packages/cli-template-monorepo-ethers/apps/web-app/src/components/PageContainer.tsx#L40-L42). 

## Context

https://github.com/semaphore-protocol/semaphore/pull/841#discussion_r1805452934

**Comment by Mide001** [comment]
can you assign this to me? @vplasencia

**Comment by vplasencia** [comment]
Hey @Mide001! Thank you for the interest. 

@Chirag-S-Kotian started to work on this issue (https://github.com/semaphore-protocol/semaphore/pull/879), if they agree we will assign them the issue. 

Let's wait a bit for their answer. If they take too long to answer, we can ask you if you would like us to assign the issue to you.

**Comment by Mide001** [comment]
alright

**Comment by Chirag-S-Kotian** [comment]
yes i can fix this ,i will accept this.
