### ISSUE TITLE
Create version of boilerplate that the PSE team can use for surveys (?)

### ISSUE THREAD

**Issue by rachelaux** [semaphore-protocol/boilerplate#9]

**Comment by rachelaux** [comment]
Can i get permission to update issues? I can't add labels or anything

**Comment by rachelaux** [comment]
this seems like something that the team wants to use the boilerplate for but I feel like the current boilerplate was designed for a different use case: educating devs who are learning about Semaphore. What do you think of creating a specific survey tool for the team?

**Comment by cedoor** [comment]
> Can i get permission to update issues? I can't add labels or anything

You should be able to update it now! Let me know.

> this seems like something that the team wants to use the boilerplate for but I feel like the current boilerplate was designed for a different use case: educating devs who are learning about Semaphore. What do you think of creating a specific survey tool for the team?

I really like the idea! I added a new board with some tasks (https://github.com/orgs/semaphore-protocol/projects/10/views/8) for a boilerplate v3, which can easily be extended and used to create other PSE apps with Semaphore.
